### Movies all_movies
GET http://localhost:3000/movies.json 

### Movies
GET http://localhost:3000/movies/2.json 

### Display Body Param
POST http://localhost:3000/localhost:3000/movies.json
content-type: application/json

{
  "title": "I'm a movie"
}