### Actors Index
GET http://localhost:3000/actors.json 

### Actors Create
POST http://localhost:3000/actors.json
Content-Type: application/json

{
"first_name": "Test Name",
"last_name": "Test Last Name",
"known_for": "Test thing they're known for"
}

### Actors Show
GET http://localhost:3000/actors/9.json

### Actors Update
PATCH http://localhost:3000/actors/9.json 
Content-Type: application/json

{
"first_name": "New First Name",
"last_name": "New Last Name",
"known_for": "Something Else Known For"
}

# ### Display Body Param for movie
# POST http://localhost:3000/localhost:3000/movies.json
# content-type: application/json

# {
#   "title": "I'm a movie"
# }

### Actors Destroy
DELETE http://localhost:3000/actors/1.json

### Movies Index
GET http://localhost:3000/movies.json 

### Movies Create
POST http://localhost:3000/movies.json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2NTgyNDEwNjV9.cj_jgV_0TUpgvSHzCW3DSvIF3Uyssqp7UwI1d3DQI1Y
Content-Type: application/json

{
"title": "Test Title",
"year": 2032,
"plot": "Test Plot"
}

### Movies Show
GET http://localhost:3000/movies/1.json

### Movies Update
PATCH http://localhost:3000/movies/3.json 
Content-Type: application/json

{
  "title": "New Title",
  "year": 2020,
  "plot": "New Plot"
}

# ### Display Body Param
# POST http://localhost:3000/localhost:3000/movies.json
# content-type: application/json

# {
#   "title": "I'm a movie"
# }

### Movies Destroy
DELETE http://localhost:3000/movies/2.json

### Users create (signup)
POST http://localhost:3000/users.json
Content-Type: application/json

{
  "name": "Test name 3",
  "email": "testers@test.com",
  "password": "password",
  "password_confirmation": "password"
}

### Sessions create (login)
POST http://localhost:3000/sessions.json
Content-Type: application/json

{
  "email": "test@test.com",
  "password": "password"
}

### MovieGenre Create
POST http://localhost:3000/movie_genre.json
Content-Type: application/json

{
  "movie_id": "Test",
  "genre_id": "Test"
}